
# Copyright (C) 2023 Kendall Tauser
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

---

name: Golang CI

on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - "*"
    tags:
    - "*"

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Set Directory
      if: ${{ env.APP_DIR != '' }}
      run: cd ${{ env.APP_DIR }}
    - name: Build Binary
      run: mage build${{ env.APP_NAME }}

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Set Directory
      if: ${{ env.APP_DIR != '' }}
      run: cd ${{ env.APP_DIR }}
    - name: Run tests
      run: if [ "$CGO_ENABLED" == "1" ]; then go test -v -cover -race ./...; else go test -v -cover ./...; fi

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Set Directory
      if: ${{ env.APP_DIR != '' }}
      run: cd ${{ env.APP_DIR }}
    - name: Install linter
      run: go install mvdan.cc/gofumpt@latest
    - name: Lint
      run: test -z "$(gofumpt -d -e $(git ls-files '*.go'))"
      
  vet:
    name: vet
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Set Directory
      if: ${{ env.APP_DIR != '' }}
      run: cd ${{ env.APP_DIR }}
    - name: Vet
      run: go vet -v ./...
