
# Copyright (C) 2025 Kendall Tauser
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

---

name: Containers CD
on: 
  workflow_call:
    inputs:
      APP_NAME:
        description: Specify the name of your application within the repo to run CI against.
        default: ""
        required: true
        type: string
      VERSION:
        description: Specify the version of the container to push.
        default: ""
        required: true
        type: string
      DOCKERFILE_PATH:
        description: Specify the path to the Dockerfile to build and publish.
        default: Dockerfile
        required: false
        type: string
      DOCKERFILE_CONTEXT:
        description: Specify the context for the Dockerfile to build and publish.
        default: .
        required: false
        type: string

permissions:
  packages: write
  contents: read

jobs:
  build-push:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Image
      uses: redhat-actions/buildah-build@v2.13
      with:
        containerfiles: ${{ inputs.DOCKERFILE_PATH }}
        context: ${{ inputs.DOCKERFILE_CONTEXT }}
        image: ghcr.io/${{ github.repository_owner }}/${{ inputs.APP_NAME }}
        tags: latest ${{ inputs.VERSION }}
        layers: true
    - name: Push Image
      uses: redhat-actions/push-to-registry@v2.8
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        image: ${{ inputs.APP_NAME }}
        tags: latest ${{ inputs.VERSION }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tls-verify: true
